### ISSUE TITLE
Add cURL Request Headers

### ISSUE THREAD

**Issue by Stevechaput** [barbushin/multirequest#3]
Hello - 

Love this library - can't thank you enough for it.  However, I'm trying to find a way to send alternate header content types.  For example, the URL I'm trying to query returns data in XML, and I would like to get the data back in JSON form.  Their support has informed me I need to "pass the header value of 
```Content-Type: application/json; charset=utf-8"```

I've tried modifying line 139 in Request.php
```$this->addHeader('Content-Type:	application/x-www-form-urlencoded; charset=' . $clientEncoding);```

I've also tried adding an array element to the protected $headers variable in Request.php
```protected $headers = array('Expect:','application/json');```

but neither of these options seem to return the data in JSON.

Am I on the right track with my thinking, or is it something I need to get back in touch with their support?  I would appreciate any guidance on this topic!

Thanks again!

**Comment by barbushin** [comment]
Fixed. Thanks for report! :+1:
