### ISSUE TITLE
mb_convert_encoding(): Illegal character encoding specified

### ISSUE THREAD

**Issue by ncla** [barbushin/multirequest#4]
Line 233 in Request.php

`$this->responseContent` is 

```
string(188) "
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html>
<head>
<link rel="stylesheet" type="text/css" href="int2.css">
</head>
<body>
B&#322;&#261;d. Brak numeru paczki.
</body></html>
"
```

`$this->serverEncoding` is `string(5) "utf-8"` 

and 

`$clientEncoding` is `string(12) "windows-1250"`

PHP 5.5.9-1ubuntu4.9 (cli)

**Comment by barbushin** [comment]
For now, just try to replace `mb_convert_encoding` call to something like `iconv('WINDOWS-1250', 'UTF-8//IGNORE', $data);` and report me if it works, I'll update MultiRequest to use `iconv` as alternative if `mb_convert_encoding` not works.

**Comment by ncla** [comment]
Tried
`$this->responseContent = iconv($clientEncoding, $this->serverEncoding, $this->responseContent);`
and I get 
`iconv(): Wrong charset, conversion from `win-1251' to `utf-8' is not allowed` now.

Right now I just ended up doing this as I don't really care for the response, in my case.

```
try {
    $this->responseContent = mb_convert_encoding($this->responseContent, $this->serverEncoding, $clientEncoding);
} catch (\ErrorException $e) {
    $this->responseContent = "";
}
```

**Comment by barbushin** [comment]
Try to replace `win-1251` with `windows-1251` or `cp1251`.

**Comment by ncla** [comment]
Apologies for late reply.

It seems that it did the trick, but I stumbled upon new encoding 'euc-jp' which `inconv()` doesn't like.
```
  [ErrorException]                                        
  iconv(): Detected an illegal character in input string  
```

**Comment by barbushin** [comment]
So you can check if `@iconv()` return false, then use `mb_convert_encoding`.
